<!-- start my courageous dates -->
<tr>
<td colspan="2"><font><B>My Courageous</B> (Matt & John from Charlene)</td>
</tr>
<tr>
<td align="left" valign="top"><font>6/29/05&nbsp;</td>
<td align="left" valign="top"><font>Wed - Cambridge, MA - <a href="http://www.mideastclub.com/zuzu/" target="_top">ZuZu</a>. w/ E.R. (featuring Eldridge from <a href="http://www.thebeatings.com/" target="_top">The Beatings</a>).</td>
</tr>
<tr>
<td align="left" valign="top"><font>7/21/05&nbsp;</td>
<td align="left" valign="top"><font>Thur - Cambridge, MA - <a href="http://www.mideastclub.com/zuzu/" target="_top">ZuZu</a>. w/ TBD.<br><br></td>
</tr>
<!-- end my courageous dates -->
<!-- start broken river prophet dates -->
<tr>
<td colspan="2"><font><B>Broken River Prophet (mems of Lockgroove, Mistle Thrush & the Also-Rans)</B></td>
</tr>
</tr>
<tr>
<td align="left" valign="top"><font>5/22/2004&nbsp;</td>
<td align="left" valign="top"><font>Sat - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's Place</a>. W/ <a href="http://www.subarachnoid.com/" target="_top">Subarachnoid Space</a> & <a href="http://www.acidmothers.com/" target="_top">Acid Mothers Temple</a>.<br><br></td>
</tr>
<tr>
<td align="left" valign="top"><font>9/30/2003&nbsp;</td>
<td align="left" valign="top"><font>Tue - Allston, MA - <a href="http://www.fanatticrecords.com/obrienshome.html" target="_top">O'Brien's</a> w/ <a href="http://www.myeducationmusic.com/" target="_top">My Education</a> (fr. Austin, TX), <a href="http://www.geocities.com/mexico1910nola/" target="_top">Mexico 1910</a> (fr. New Orleans) and <a href="http://www.sharkmountainband.com/" target="_top">Shark Mountain</a>.<br><br></td>
</tr>
<!-- end broken river prophet dates -->
<!-- start charlene+HA dates -->
<tr>
<td colspan="2"><font><B>Charlene & Hello, Attack!</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>3/17/2002&nbsp;</td>
<td align="left" valign="top"><font>Sun - Cambridge, MA - <a href="http://www.mideastclub.com/" target="_top">The Middle East  Upstairs</a> w/ <a href="http://www.thebeatings.com/" target="_top">The Beatings</a> & Blacktail.<br><br></td>
</tr>
<!-- end charlene+HA dates -->
<!-- start special event dates -->
<tr>
<td colspan="2"><font><B>3.5eps Compilation Release Party</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>1/26/2002&nbsp;</td>
<td align="left" valign="top"><font>Sat - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">TT the Bears Place</a> w/ <a href="http://www.lockgroove.com/" target="_top">Lockgroove</a>, Charlene, HelloAttack! & Compass<br><br></td>
</tr>
<!-- end special event dates -->
