<!-- start charlene dates -->
<tr>
<td colspan="2"><font><B>Charlene - 2005</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>12/3/05&nbsp;</td>
<td align="left" valign="top"><font>Mon - Cambridge, MA - The Lizard Lounge (1667 Massachusetts Avenue). w/ <a href="http://www.theburdocks.com/" target="_top">Burdocks</a>, <a href="http://www.anorthernchorus.com/" target="_top">A Northern Chorus</a>, & Oh no Dinosaur!</td>
</tr>
<tr>
<td align="left" valign="top"><font>8/11/05&nbsp;</td>
<td align="left" valign="top"><font>Thur - Cambridge, MA - <a href="http://www.mideastclub.com" target="_top">The Middle East</a> (down).  w/ <a href="http://www.dragcity.com/bands/smog.html" target="_top">Smog</a> & <a href="http://www.feathersfamily.org/" target="_top">Feathers</a>. 18+ $12</td>
</tr>
<tr>
<td align="left" valign="top"><font>8/1/05&nbsp;</td>
<td align="left" valign="top"><font>Mon - Cambridge, MA - The Lizard Lounge (1667 Massachusetts Avenue).  w/ <a href="http://www.sianspheric.com/" target="_top">Sianspheric</a> & <a href="http://www.anorthernchorus.com/" target="_top">A Northern Chorus</a>. <i>Presented by WZBC's <a href="http://www.wzbc.org" target="_top">Flyweight</a>.</i></td>
</tr>
<tr>
<td align="left" valign="top"><font>7/30/05&nbsp;</td>
<td align="left" valign="top"><font>Sat - New York, NY - <a href="http://thetrashbar.com/" target="_top">The Trash Bar</a>. w/ <a href="http://wwww.brokenriverprophet.com" target="_top">The Broken River Prophet</a>, Cindy from <a href="http://www.caulfieldsisters.com/" target="_top">The Caulfield Sisters</a>, <a href="http://www.picastro.net/" target="_top">Picastro</a> & Brain Bonz & the Fort Green District. $8, 21+. Karaoke after party!</td>
</tr>
<tr>
<td align="left" valign="top"><font>7/9/05&nbsp;</td>
<td align="left" valign="top"><font>Sat - Cambridge, MA - <a href="http://www.mideastclub.com" target="_top">The Middle East</a> (down). w/ <a href="http://www.bettieserveert.com/" target="_top">Bettie Serveert</a>. $12, 18+.</td>
</tr>
<tr>
<td align="left" valign="top"><font>6/4/05&nbsp;</td>
<td align="left" valign="top"><font>Sat - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's</a>. w/ <a href="http://www.americanmary.com/" target="_top">The National</a>, <a href="http://www.cottonponies.com/" target="_top">Cotton Ponies</a> & <a href="http://www.pelamusic.com/" target="_top">Pela</a>. 18+, $9.</td>
</tr>
<tr>
<td align="left" valign="top"><font>4/19/05&nbsp;</td>
<td align="left" valign="top"><font>Tue - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's</a>. w/ <a href="http://www.marytimony.com/" target="_top">Mary Timony</a> & Noll.</td>
</tr>
<tr>
<td align="left" valign="top"><font>3/13/05&nbsp;</td>
<td align="left" valign="top"><font>Sun - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's</a>. w/ <a href="http://www.hoodmusic.net/" target="_top">Hood</a> & <a href="http://www.brokenriverprophet.com/" target="_top">Broken River Prophet</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>1/29/05&nbsp;</td>
<td align="left" valign="top"><font>Sat - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's</a>. w/ <a href="http://www.rohdelikat.com/" target="_top">Roh Delikat</a>, <a href="http://www.bonsavants.com" target="_top">The Bon Savants</a> & <a href="http://www.dear-leader.com/" target="_top">Dear Leader</a>.<br><br></td>
</tr>
<tr>
<td colspan="2"><font><B>Charlene - 2004</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>11/7/04&nbsp;</td>
<td align="left" valign="top"><font>Sun - Cambridge, MA - <a href="http://www.mideastclub.com/" target="_top">Middle East Up</a>. w/ <a href="http://www.southern.com/karate" target="_top">Karate</a> (rec. release show!) & <a href="http://www.helmsmusic.com/" target="_top">Helms</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>6/27/2004&nbsp;</td>
<td align="left" valign="top"><font>Sun - Philadelphia, PA ­ <a href="http://www.popnoisefest.com/" target="_top">POPNOISE Festival</a>. The Rotunda. 4014 Walnut Street. All ages. $Free. 11am - Midnight. Featuring Aplacetoburystrangers, Brasilia, Alcian Blue, Autodrone, Stellarscope, etc. Too many to name!</td>
</tr>
<tr>
<td align="left" valign="top"><font>6/26/2004&nbsp;</td>
<td align="left" valign="top"><font>Sat - New York, NY - <a href="http://www.tribecarockclub.com" target="_top">Tribeca Rock Club</a>. w/ <a href="http://www.exitclov.com/" target="_top">Exit Clov</a> & <a href="http://www.bedouinthieves.com/" target="_top">The Bedouin Thieves</a>. 16 Warren Street in downtown Manhattan. 1 Block south of Chambers Street, between Church & Broadway.</td>
</tr>
<tr>
<td align="left" valign="top"><font>6/25/2004&nbsp;</td>
<td align="left" valign="top"><font>Fri - Dartmouth, NH - FUEL Rock Club at Collis Hall. Doors 8:30pm. Presented by Friday Night Rock.</td>
</tr>
<tr>
<td align="left" valign="top"><font>6/24/2004&nbsp;</td>
<td align="left" valign="top"><font>Thur - Cambridge, MA - <a href="http://www.mideastclub.com" target="_top">The Middle East Upstairs</a>. w/ <a href="http://www.kimcheerecords.com/bands/victoryatsea/" target="_top">Victory At Sea</a>, & <a href="http://www.thepaperchaseband.com/" target="_top">The Paper Chase</a>. 18+ Doors 9pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>5/9/04&nbsp;</td>
<td align="left" valign="top"><font>Sun - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's Place</a>. W/ <a href="http://www.perishablerecords.com/califone.html" target="_top">Califone</a> & Drew O'Doherty.</td>
</tr>
<tr>
<td align="left" valign="top"><font>5/07/04&nbsp;</td>
<td align="left" valign="top"><font>Fri - New York, NY - <a href="http://www.tribecarockclub.com/" target="_top">Tribeca Rock Club</a>. w/ <a href="http://www.theargument.net/" target="_top">The Argument</a>, <a href="http://www.picpockets.net/" target="_top">The Picpockets</a> & <a href="http://www.averimusic.com/" target="_top">Averi</a><BR><BR></td>
</tr>
<tr>
<td colspan="2"><font><B>Charlene - 2003</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>10/16/03&nbsp;</td>
<td align="left" valign="top"><font>Thur - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's Place</a>. W/ <a href="http://www.ironandwine.com/" target="_top">Iron & Wine</a> & <a href="http://www.jessesykes.com" target="_top">Jesse Sykes and the Sweet Hereafter</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>10/10/03&nbsp;</td>
<td align="left" valign="top"><font>Fri - Fitchburg, MA - <a href="http://www.thedovetailgroup.org/" target="_top">Free Space Gallery</a>. w/ <a href="http://www.thefuries3.com/" target="_top">The Furies</a> & <a href="http://www.kimcheerecords.com/bands/seanacarmody/" target="_top">Seana Carmody</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>9/20/03&nbsp;</td>
<td align="left" valign="top"><font>Sat - Hoboken, NJ - <a href="http://www.maxwellsnj.com/" target="_top">Maxwell's</a>. w/ <a href="http://www.markgardener.com/" target="_top">Mark Gardener</a> (ex-<a href="http://www.rideox4.net/" target="_top">Ride</a>) & <a href="http://www.goldrush.mu/" target="_top">Goldrush</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>9/19/03&nbsp;</td>
<td align="left" valign="top"><font>Fri - New York, NY - <a href="http://www.tribecarockclub.com/" target="_top">Tribeca Rock Club</a>. <a href="http://www.musictoday.com/buy_tickets.asp?show_id=1113070&search_type=1&club_id=43945&venue=Tribeca" target="_top"><i>Buy Tix!</i></a> w/ <a href="http://www.markgardener.com/" target="_top">Mark Gardener</a> (ex-<a href="http://www.rideox4.net/" target="_top">Ride</a>) & <a href="http://www.goldrush.mu/" target="_top">Goldrush</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>9/18/03&nbsp;</td>
<td align="left" valign="top"><font>Thu - Providence, RI. - <a href="http://www.lupos.com" target="_top">Lupo's / Met Cafe</a>. w/ <a href="http://www.markgardener.com/" target="_top">Mark Gardener</a> (ex-<a href="http://www.rideox4.net/" target="_top">Ride</a>) & <a href="http://www.goldrush.mu/" target="_top">Goldrush</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>9/17/03&nbsp;</td>
<td align="left" valign="top"><font>Wed - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's Place</a>.  <a href="http://www.ticketmaster.com/event/010036FF9B0B48D0" target="_top"><i>Buy Tix!</i></a> w/ <a href="http://www.markgardener.com/" target="_top">Mark Gardener</a> (ex-<a href="http://www.rideox4.net/" target="_top">Ride</a>) & <a href="http://www.goldrush.mu/" target="_top">Goldrush</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>9/16/03&nbsp;</td>
<td align="left" valign="top"><font>Tue - Philadelphia, PA - <a href="http://www.thekhyber.com/" target="_top">The Khyber</a>. w/ <a href="http://www.markgardener.com/" target="_top">Mark Gardener</a> (ex-<a href="http://www.rideox4.net/" target="_top">Ride</a>) & <a href="http://www.goldrush.mu/" target="_top">Goldrush</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>9/15/03&nbsp;</td>
<td align="left" valign="top"><font>Mon - Cleveland, OH - <a href="http://www.grogshop.gs/" target="_top">Grog Shop</a>. w/ <a href="http://www.markgardener.com/" target="_top">Mark Gardener</a> (ex-<a href="http://www.rideox4.net/" target="_top">Ride</a>) & <a href="http://www.goldrush.mu/" target="_top">Goldrush</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>9/13/03&nbsp;</td>
<td align="left" valign="top"><font>Sat - Chicago, IL - <a href="http://www.emptybottle.com" target="_top">Empty Bottle</a>.  <a href="http://emptybottle.musictoday.com/" target="_top"><i>Buy Tix!</i></a> w/ <a href="http://www.markgardener.com/" target="_top">Mark Gardener</a> (ex-<a href="http://www.rideox4.net/" target="_top">Ride</a>) & <a href="http://www.goldrush.mu/" target="_top">Goldrush</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>9/12/03&nbsp;</td>
<td align="left" valign="top"><font>Fri - Detroit, MI - <a href="http://cc.com/venue.asp?venueID=1779" target="_top">Shelter</a>.   <a href="http://www.ticketmaster.com/event/080036FD9F8421D4" target="_top"><i>Buy Tix!</i></a> w/ <a href="http://www.markgardener.com/" target="_top">Mark Gardener</a> (ex-<a href="http://www.rideox4.net/" target="_top">Ride</a>) & <a href="http://www.goldrush.mu/" target="_top">Goldrush</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>9/11/03&nbsp;</td>
<td align="left" valign="top"><font>Thu - Toronto, CANADA - <a href="http://www.leespalace.com" target="_top">Lee's Palace</a>. w/ <a href="http://www.markgardener.com/" target="_top">Mark Gardener</a> (ex-<a href="http://www.rideox4.net/" target="_top">Ride</a>) & <a href="http://www.goldrush.mu/" target="_top">Goldrush</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>7/09/2003&nbsp;</td>
<td align="left" valign="top"><font>Wed - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's Place</a>. w/ <a href="http://www.callamusic.com" target="_top">Calla</a> & <a href="http://www.creeperlagoon.com/" target="_top">Creeper Lagoon</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>6/29/2003&nbsp;</td>
<td align="left" valign="top"><font>Sun - New York, NY - <a href="http://www.mercuryloungenyc.com/" target="_top">Mercury Lounge</a>.  w/ <a href="http://www.themobiusband.com/" target="_top">Mobius Band</a> & <a href="http://www.canyonrock.com/" target="_top">Canyon</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>6/28/2003&nbsp;</td>
<td align="left" valign="top"><font>Sat - Northampton, MA - Harry's.  w/ <a href="http://www.themobiusband.com/" target="_top">Mobius Band</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>6/27/2003&nbsp;</td>
<td align="left" valign="top"><font>Fri - Cambridge, MA - <a href="http://boston.citysearch.com/profile/4745814/" target="_top">The Lizard Lounge</a>. w/ <a href="http://www.themobiusband.com/" target="_top">Mobius Band</a>. <font class="new"><a href="http://www.virtuous.com/search/events_venue.php?venueid=THELI" target="_top">Buy tix here!</a></font></td>
</tr>
<tr>
<td align="left" valign="top"><font>5/24/2003&nbsp;</td>
<td align="left" valign="top"><font>Sat - Cambridge, MA - <a href="http://boston.citysearch.com/profile/4745814/" target="_top">The Lizard Lounge</a>. <a href="http://www.suntanmusic.com/" target="_top">Suntan's</a> record release party! w/ Dug Furgeson & <a href="http://www.helmsmusic.com/" target="_top">Helms</a>. <font class="new"><a href="http://www.virtuous.com/search/events_venue.php?venueid=THELI" target="_top">Buy tix here!</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>5/17/2003&nbsp;</td>
<td align="left" valign="top"><font>Sat - Fitchurgh, MA - <a href="http://www.thedovetailgroup.org" target="_top">Free Space Gallery</a>. w/ <a href="http://artists.mp3s.com/artists/372/paper_december_orchestra.html" target="_top">Paper December Orchestra</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>4/13/2003&nbsp;</td>
<td align="left" valign="top"><font>Sun - Philadelphia, PA - <a href="http://www.thekhyber.com/" target="_top">The Khyber Pass</a>. w/ Bloodthirsty Lovers.</td>
</tr>
<tr>
<td align="left" valign="top"><font>4/12/2003&nbsp;</td>
<td align="left" valign="top"><font>Sat - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's Place</a>. w/ <a href="http://www.frenchkissrecords.com" target="_top">Bloodthirsty Lovers</a>, <a href="http://www.lockgroove.com/" target="_top">Lockgroove</a> & <a href="http://www.suntan4ever.com/" target="_top">Suntan</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>4/11/2003&nbsp;</td>
<td align="left" valign="top"><font>Fri - Durham, NH - University of New Hampshire. w/ <a href="http://www.frenchkissrecords.com" target="_top">Bloodthirsty Lovers</a> & <a href="http://www.lockgroove.com/" target="_top">Lockgroove</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>4/10/2003&nbsp;</td>
<td align="left" valign="top"><font>Thu - New York, NY - <a href="http://www.mercuryloungenyc.com" target="_top">The Mercury Lounge</a>. w/ <a href="http://www.frenchkissrecords.com" target="_top">Bloodthirsty Lovers</a>, <a href="http://www.lockgroove.com/" target="_top">Lockgroove</a> & The National.</td>
</tr>
<tr>
<td align="left" valign="top"><font>4/8/2003&nbsp;</td>
<td align="left" valign="top"><font>Tue - Cambridge, MA - <a href="http://www.wmbr.org/" target="_top">WMBR 88.1fm</a>. Live performance on <a href="http://www.wmbr.org/shows/pipeline.html" target="_top">Pipeline!</a> 8pm.</td>
</tr>
</tr>
<tr>
<td align="left" valign="top"><font>3/26/2003&nbsp;</td>
<td align="left" valign="top"><font>Wed - Medford, MA - <a href="http://www.wmfo.org" target="_top">WMFO 91.5fm</a>. Live performance on the "<a href="http://druglessdouglas.com/ott/" target="_top">On the Town w/ Mikey Dee</a>" show. 9pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>1/29/2003&nbsp;</td>
<td align="left" valign="top"><font>Wednesday - 91.5fm - <a href="http://www.wmfo.org" target="_top">WMFO</a> - Live broadcast on <a href="http://www.druglessdouglas.com/ott/" target="_top">OTT</a>. <font class="new">CANCELLED</font></td>
</tr>
<tr>
<td align="left" valign="top"><font>1/27/2003&nbsp;</td>
<td align="left" valign="top"><font>Monday - Cambridge, MA - <a href="http://www.mideastclub.com" target="_top">The Middle East - Up</a>. W/ <a href="http://www.kimcheerecords.com/catalog/kc021/" target="_top">Suntan</a>, <a href="http://www.liquortricks.com/" target="_top">Liquor Tricks</a> & All Night. <font class="new">CANCELLED</font><br><br></td>
</tr>
<tr>
<td colspan="2"><font><B>Charlene - 2002</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>11/8/2002&nbsp;</td>
<td align="left" valign="top"><font>Friday - New York, NY - Pianos. 158 Ludlow St. @ Stanton.  Doors at 9:00 $8. W/ The Fever & <a href="http://circleandsquarerock.com/" target="_top">Circle and Square</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>11/2/2002&nbsp;</td>
<td align="left" valign="top"><font>Sat - Cambridge, MA - <a href="http://boston.citysearch.com/profile/4745814/" target="_top">Lizard Lounge</a>. Two set of live music from Charlene and friends. Doors at 9pm. Tickets on sale <a href="tix/" target="_top">here</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>8/10/2002&nbsp;</td>
<td align="left" valign="top"><font>Sat - Providence, RI - <a href="http://go.to/safariri" target="_top">Safari Lounge </a> w/  <a href="http://www.superface.tv" target="_top">Superface</a>, <a href="http://www.seriouslygroovy.com/emetrex.htm" target="_top">Emetrex</a>, & <a href="http://lostaudionetwork.com/" target="_top">Lost Audio Network</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>8/3/2002&nbsp;</td>
<td align="left" valign="top"><font>Sat - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's Place</a> w/ <a href="http://www.herspaceholiday.com/" target="_top">Her Space Holiday</a> & <a href="http://www.americananalogset.com/" target="_top">American Analog Set</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>7/11/2002&nbsp;</td>
<td align="left" valign="top"><font>Thu - Somerville, MA - <a href="http://www.bar608.com/" target="_top">608</a> w/ <a href="http://www.seriouslygroovy.com/emetrex.htm" target="_top">Emetrex</a> & <a href="http://www.superface.tv" target="_top">Superface</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>6/22/2002&nbsp;</td>
<td align="left" valign="top"><font>Sat - Durham, NH - <a href="http://wunh.unh.edu/" target="_top">WUNH 91.3fm</a> live on "Playing With Knobs" 3-6pm</td>
</tr>
<tr>
<td align="left" valign="top"><font>5/18/2002&nbsp;</td>
<td align="left" valign="top"><font>Sat - Cambridge, MA - <a href="http://boston.citysearch.com/profile/4745814/" target="_top">The Lizard Lounge</a> w/ <a href="http://www.seriouslygroovy.com/emetrex.htm" target="_top">Emetrex</a> & <a href="http://www.superface.tv" target="_top">Superface</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>3/15/2002&nbsp;</td>
<td align="left" valign="top"><font>Fri - Chicago, IL - <a href="http://www.mpshows.com" target="_top">Fireside Bowl</a> w/ <a href="http://www.theataristar.com/" target="_top">The Atari Star</a> & <a href="http://www.writteninthesand.com/" target="_top">Written in the Sand</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>3/13/2002&nbsp;</td>
<td align="left" valign="top"><font>Wed - Austin, TX - <a href="http://www.sxsw.com" target="_top">SXSW</a>: <a href="http://www.candygrambooking.com" target="_top">The Candy Gram Booking Showcase</a> @ The Rehab Lounge w/ <a href="http://www.audioexplorations.com" target="_top">Audio Explorations</a>, <a href="http://www.tracyshedd.com/" target="_top">Tracy Shedd</a>, and <a href="http://www.versus-ny.co.uk/" target="_top">+ / -</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>3/12/2002&nbsp;</td>
<td align="left" valign="top"><font>Tue - Houston, TX - <a href="http://www.handsuphouston.com" target="_top">Mary Jane's</a> w/ <a href="http://www.teamusarocks.com" target="_top">Team USA</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>3/11/2002&nbsp;</td>
<td align="left" valign="top"><font>Mon - Baton Rouge, LA - <a href="http://www.spanishmoon.org/" target="_top">Spanish Moon</a> w/ The 101 (ex-Antartica and Christy Front Drive), <a href="http://www.thedrapes.com/" target="_top">The Drapes</a>, & <a href="http://www.the-shams.com/" target="_top">Thee Shams</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>3/9/2002&nbsp;</td>
<td align="left" valign="top"><font>Sat - Arlington, VA - <a href="http://www.galaxyhut.com/" target="_top">Galaxy Hut</a> w/ <a href="http://www.bradykynin.com/" target="_top">Bradykynin</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>2/19/2002&nbsp;</td>
<td align="left" valign="top"><font>Tue - Durham, NH - <a href="http://www.unh.edu/" target="_top">University of New Hampshire</a> w/ <a href="http://www.audioexplorations.com/" target="_top">Audio Explorations</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>2/18/2002&nbsp;</td>
<td align="left" valign="top"><font>Mon - Cambridge, MA - <a href="http://www.thekendall.com/" target="_top">The Kendall Cafe</a> w/ <a href="http://www.audioexplorations.com/" target="_top">Audio Explorations</a><br><br></td>
</tr>
<tr>
<td colspan="2"><font><B>Charlene - 2001</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>11/10/2001&nbsp;</td>
<td align="left" valign="top"><font>Sat - Easthampton, MA - <a href="http://www.flywheelarts.org/" target="_top">Flywheel</a> w/ <a href="http://www.fiftyfourfortyorfight.com/" target="_top">The Double</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>11/9/2001&nbsp;</td>
<td align="left" valign="top"><font>Fri - Buffalo, NY - Gala South Loft</td>
</tr>
<tr>
<td align="left" valign="top"><font>11/8/2001&nbsp;</td>
<td align="left" valign="top"><font>Thu - Columbus, OH - <a href="http://www.cringe.com/bs/distillery.htm" target="_top">Bernies Distillery</a> w/ <a href="http://www.peekaboorecords.com/bands/wontons/" target="_top">The Wontons</a> & Kabochack (from Japan)</td>
</tr>
<tr>
<td align="left" valign="top"><font>11/7/2001&nbsp;</td>
<td align="left" valign="top"><font>Wed - Louisville, KY - <a href="http://www.therudyardkipling.com/" target="_top">The Rudyard Kipling</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>11/6/2001&nbsp;</td>
<td align="left" valign="top"><font>Tue - Chapel Hill, NC - <a href="http://www.chapel-hill.nc.us/clubs/index.html" target="_top">Go! Rehearsal Studios</a> w/ <a href="http://www.audioexplorations.com" target="_top">Audio Explorations</a> & Projections by <a href="http://www.radartheory.com" target="_top">RADARtheory</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>11/5/2001&nbsp;</td>
<td align="left" valign="top"><font>Mon - Greenville, NC - Back Door Skate Park w/ <a href="http://www.audioexplorations.com" target="_top">Audio Explorations</a> & Projections by <a href="http://www.radartheory.com" target="_top">RADARtheory</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>11/4/2001&nbsp;</td>
<td align="left" valign="top"><font>Sun - Charlotte, NC - Fat City w/ <a href="http://www.audioexplorations.com" target="_top">Audio Explorations</a> & Projections by <a href="http://www.radartheory.com" target="_top">RADARtheory</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>11/3/2001&nbsp;</td>
<td align="left" valign="top"><font>Sat - Wilmington, NC - 3rd Floor on Princess w/ <a href="http://www.spineless.com/trackstar.html" target="_top">Track Star</a> & Projections by <a href="http://www.radartheory.com" target="_top">RADARtheory</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>11/2/2001&nbsp;</td>
<td align="left" valign="top"><font>Fri - West Chester, PA - <a href="http://www.rexsbar.com" target="_top">Rex's Bar</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>11/1/2001&nbsp;</td>
<td align="left" valign="top"><font>Thu - New York, NY - <a href="http://www.browniesnyc.com/" target="_top">Brownies</a> w/ <a href="http://www.beeandflower.com/" target="_top">Bee and Flower</a>, <a href="http://www.darediablo.com/" target="_top">Darediablo</a>, & Acosm. 21+ $8. Doors at 8pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>10/11/2001&nbsp;</td>
<td align="left" valign="top"><font>Thu - Central Square, MA. - <a href="http://www.mideastclub.com" target="_top">The MiddleEast Upstairs</a> w/ <a href="http://www.brainwashed.com/fridge" target="_top">Fridge</a> & <a href="http://www.landingsite.net/" target="_top">Landing</a>.<br><br></td>
</tr>
<!-- end charlene dates -->
