<!-- start compass dates
<tr>
<td colspan="2"><font><B>Compass</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>4/10/2004&nbsp;</td>
<td align="left" valign="top"><font>Sat - Jamaica Plain, MA - Space 44 (44 Green Street). 8:30pm, $4 suggested donation. </a> w/ J.P. Juliet Kilo, <a href="http://www.xmatpatx.com" target="_top">The Specific Heats</a> & <a href="http://www.uvprotectyou.com" target="_top">U.V. Protection</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>5/18/2004&nbsp;</td>
<td align="left" valign="top"><font>Tue - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's Place</a>. 9pm, $8. </a> w/ <a href="http://www.thestandardsite.com/" target="_top">The Standard</a>.<BR><BR></td>
</tr>
end compass dates -->