<!-- end Charlene dates -->
<tr> 
<td colspan="2"><font><B>Charlene</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>6/04/06&nbsp;</td>
<td align="left" valign="top"><font>Sun - Somerville, MA - <a href="http://www.paslounge.com/" target="_top">PA's Lounge</a>. w/ <a href="http://www.100songsising.com/" target="_top">Josephine Foster</a> & <a href="http://www.northeastindie.com/micah/" target="_top">Micah Blue Smaldone</a>. Presented by the <a href="http://www.thecritique.org" target="_top">Critique of Pure Reason</a>. $8, 21+.</td>
</tr>
<tr>
<td align="left" valign="top"><font>6/01/06&nbsp;</td>
<td align="left" valign="top"><font>Thur - New York, NY - <a href="http://thetrashbar.com/" target="_top">The Trash Bar</a>. w/ Can't Face the Falling, Soal, Second Dan, & The Ruling Party. $6, 21+.</td>
</tr>
<tr>
<td align="left" valign="top"><font>5/17/06&nbsp;</td>
<td align="left" valign="top"><font>Wed - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's</a>. w/ <a href="http://www.yearfuture.net/" target="_top">Year Future</a>, <a href="http://www.thewithlove.org/" target="_top">The With Love</a>, & <a href="http://www.ketman.net/" target="_top">Ketman</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>3/8/06&nbsp;</td>
<td align="left" valign="top"><font>Wed - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's</a>. w/ <a href="http://www.serena-maneesh.com/" target="_top">Serena Maneesh</a> & <a href="http://www.appletowngunshop.com/" target="_top">Appletown Gun Shop</a><br><br></td>
</tr>
<!-- end Charlene dates -->
