<!-- start HA dates
<tr>
<td colspan="2"><font><B>Hello, Attack!</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>4/24/2003&nbsp;</td>
<td align="left" valign="top"><font>Thu - Boston, MA - <a href="http://boston.cc.com/paradise.asp" target="_top">The Paradise Lounge</a>. J will also be DJing. Presented by the <a href="http://www.weeklydig.com/" target="_top">WeeklyDig</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>5/2/2003&nbsp;</td>
<td align="left" valign="top"><font>Fri - Cambridge, MA - <a href="http://www.mideastclub.com" target="_top">The Middle East (Upstairs)</a>. w/ <a href="http://www.acefu.com/modules.php?op=modload&name=News&file=article&sid=80&mode=thread&order=0&thold=0" target="_top">Officer May</a> <i>release party!</i>, <a href="http://www.eyeslikeknives.com/" target="_top">Eyes Like Knives</a> & <a href="http://www.polarismine.com/" target="_top">Polaris Mine</a><br><br></td>
</tr>
end HA dates -->