<!-- start lockgroove dates -->
<tr>
<td colspan="2"><font><B>Lockgroove - Fall 2004</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>10/8/2004&nbsp;</td>
<td align="left" valign="top"><font>Fri - Cambridge, MA ­ <a href="http://www.ttthebears.com/" target="_top">T.T. the Bear's Place</a> <font class="new">CD RELEASE PARTY!!</font>. w/ <a href="http://www.stinkyrecords.com/stinky_artists/singapore_sling.html" target="_top">Singapore Sling</a> (Stinky Records, From Iceland), <a href="http://www.hopewell.tv/" target="_top">Hopewell</a> (mems of Mercury Rev), and <a href="http://www.thesubject.net/" target="_top">The Subject</a><BR><BR></td>
</tr>
<tr>
<td align="left" valign="top"><font>11/5/2004&nbsp;</td>
<td align="left" valign="top"><font>Fri - Cambridge, MA ­ <a href="http://www.mideastclub.com/" target="_top">Middle East Downstairs</a> w/ <a href="http://www.fuzzywuzzy.com" target="_top">Luna</a>. 8:30pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>11/6/2004&nbsp;</td>
<td align="left" valign="top"><font>Sat - New York, NY ­ <a href="http://www.donhills.com/" target="_top">Don Hill's</a> w/ Passenger and <a href="http://www.livingthingsmusic.com" target="_top">Living Things</a>. 9pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>11/7/2004&nbsp;</td>
<td align="left" valign="top"><font>Sun - Philadelphia, PA ­ <a href="http://www.thekhyber.com/" target="_top">The Khyber</a> w/ <a href="http://www.silentleague.com" target="_top">The Silent League</a> (x/Mercury Rev) and The Complete Strategist. 9pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>11/8/2004&nbsp;</td>
<td align="left" valign="top"><font>Mon - Arlington, VA ­ <a href="http://www.galaxyhut.com/" target="_top">Galaxy Hut</a> 8:30 pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>11/9/2004&nbsp;</td>
<td align="left" valign="top"><font>Tue - Asheville, NC ­ <a href="http://www.vincentsearcafe.com/" target="_top">Vincent's Ear</a> w/ <a href="http://www.goodluckcricket.com/hellsayers/" target="_top">Wayne Robbins & the Hellsayers</a>. 8:30 pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>11/10/2004&nbsp;</td>
<td align="left" valign="top"><font>Wed - Knoxville, TN ­ <a href="http://www.thepilotlight.com/" target="_top">The Pilot Light</a> w/ <a href="http://www.goodluckcricket.com/hellsayers/" target="_top">Wayne Robbins & the Hellsayers</a>. 8:30 pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>11/11/2004&nbsp;</td>
<td align="left" valign="top"><font>Thur - Columbus, OH ­ <a href="http://www.cringe.com/bs/distillery.htm" target="_top">Bernie's Distillery</a> w/ <a href="http://www.seedknowledge.com/echobase/echo" target="_top">Echo Base Sound System</a>. 9:00 pm.<BR><BR></td>
</tr>
<tr>
<td colspan="2"><font><B>Lockgroove - Summer 2004</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>6/24/2004&nbsp;</td>
<td align="left" valign="top"><font>Thur - Cambridge, MA - <a href="http://www.mideastclub.com" target="_top">The Middle East Upstairs</a>. w/ <a href="http://www.kimcheerecords.com/bands/victoryatsea/" target="_top">Victory At Sea</a>, & <a href="http://www.thepaperchaseband.com/" target="_top">The Paper Chase</a>. 18+ Doors 9pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>6/25/2004&nbsp;</td>
<td align="left" valign="top"><font>Fri - Dartmouth, NH - FUEL Rock Club at Collis Hall. Doors 8:30pm. Presented by Friday Night Rock.</td>
</tr>
<tr>
<td align="left" valign="top"><font>6/26/2004&nbsp;</td>
<td align="left" valign="top"><font>Sat - New York, NY - <a href="http://www.tribecarockclub.com" target="_top">Tribeca Rock Club</a>. w/ <a href="http://www.exitclov.com/" target="_top">Exit Clov</a> & <a href="http://www.bedouinthieves.com/" target="_top">The Bedouin Thieves</a>. 16 Warren Street in downtown Manhattan. 1 Block south of Chambers Street, between Church & Broadway.</td>
</tr>
<tr>
<td align="left" valign="top"><font>6/27/2004&nbsp;</td>
<td align="left" valign="top"><font>Sun - Philadelphia, PA ­ <a href="http://www.popnoisefest.com/" target="_top">POPNOISE Festival</a>. The Rotunda. 4014 Walnut Street. All ages. $Free. 11am - Midnight. Featuring Aplacetoburystrangers, Brasilia, Alcian Blue, Autodrone, Stellarscope, etc. Too many to name!<BR><BR></td>
</tr>
<tr>
<td colspan="2"><font><B>Lockgroove - Spring 2004</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>4/29/2004&nbsp;</td>
<td align="left" valign="top"><font>Thur - Cambridge, MA - <a href="http://www.mideastclub.com" target="_top">The Middle East Downstairs</a>. w/ <a href="http://www.elefantweb.com/ " target="_top">Elefant</a>, & <a href="http://www.matadorrecords.com/seachange" target="_top">Seachange</a>. Doors 8:30pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>5/14/2004&nbsp;</td>
<td align="left" valign="top"><font>Fri - Dartmouth, NH - FUEL Rock Club at Collis Hall. w/ Oh No Dinosaur!. Doors 8:30pm. Presented by Friday Night Rock.<BR><BR></td>
</tr>
<tr>
<td colspan="2"><font><B>Lockgroove - Summer 2003</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>6/10/2003&nbsp;</td>
<td align="left" valign="top"><font>Tue - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's Place</a>. w/ <a href="http://www.twistedvillage.com/ " target="_top">Major Stars</a>, <a href="http://www.subarachnoid.com" target="_top">Subarachnoid Space</a>, & <a href="http://www.brightsounds.com" target="_top">Bright</a>.<br><br></td>
</tr>
<tr>
<td colspan="2"><font><B>Lockgroove - Spring 2003</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>4/10/2003&nbsp;</td>
<td align="left" valign="top"><font>Thu - New York, NY - <a href="http://www.mercuryloungenyc.com" target="_top">The Mercury Lounge</a>. w/ <a href="http://www.frenchkissrecords.com" target="_top">Bloodthirsty Lovers</a>, Charlene & The National.</td>
</tr>
<tr>
<td align="left" valign="top"><font>4/11/2003&nbsp;</td>
<td align="left" valign="top"><font>Fri - Durham, NH - University of New Hampshire. w/ <a href="http://www.frenchkissrecords.com" target="_top">Bloodthirsty Lovers</a> & Charlene.</td>
</tr>
<tr>
<td align="left" valign="top"><font>4/12/2003&nbsp;</td>
<td align="left" valign="top"><font>Sat - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's Place</a>. w/ <a href="http://www.frenchkissrecords.com" target="_top">Bloodthirsty Lovers</a>, Charlene & <a href="http://www.suntan4ever.com/" target="_top">Suntan</a>.<br><br></td>
</tr>
<tr>
<td colspan="2"><font><B>Lockgroove - Fall 2002</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>10/11 thru 10/13/2002&nbsp;</td>
<td align="left" valign="top"><font>Boston, MA - <a href="http://www.axisnightclub.com/" target="_top">Axis</a> <a href="http://www.terrascope.org/t5.html" target="_top">Terrastock V</a> w/ Sonic Youth, Acid Mothers Temple, Bardo Pond, The Bevis Frond, Damon & Naomi, Hopewell, Lily's and many many more. <a href="http://www.terrascope.org/t5.html#tickets" target="_top">Tickets $70</a> for 3 days of amazing music.<br><br></td>
</tr>
<tr>
<td colspan="2"><font><B>Lockgroove - Spring 2002</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>5/4/2002&nbsp;</td>
<td align="left" valign="top"><font>Sat - Philadelphia, PA - <a href="http://philadelphia.citysearch.com/profile/11576373/" target="_top">Fire</a></a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>5/5/2002&nbsp;</td>
<td align="left" valign="top"><font>Sun - Arlington, VA - <a href="http://www.galaxyhut.com/" target="_top">Galaxy Hut</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>5/6/2002&nbsp;</td>
<td align="left" valign="top"><font>Mon - Columbus, OH - <a href="http://www.cringe.com/bs/distillery.htm" target="_top">Bernies Distillery</a> w/ <a href="http://www.theemeralddown.com" target="_top">Emerald Down</a> & <a href="http://www.killerrockandroll.com/" target="_top">Skywave</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>5/9/2002&nbsp;</td>
<td align="left" valign="top"><font>Thu - Toronto, CANADA - <a href="http://www.toronto.com/profile/147138/" target="_top">Rancho Relaxo</a> w/ <a href="http://www.pehrlabel.com/artists/picastro.htm" target="_top">Picastro</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>5/10/2002&nbsp;</td>
<td align="left" valign="top"><font>Fri - Montreal CANADA - <a href="http://www.montrealplus.ca/profile/76973/" target="_top">Barfly</a> w/ <a href="http://www.pehrlabel.com/artists/picastro.htm" target="_top">Picastro</a> & <a href="http://www.rainermaria.com/" target="_top">Rainer Maria</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>5/17/2002&nbsp;</td>
<td align="left" valign="top"><font>Fri - Cambridge, MA - <a href="http://www.mideastclub.com/" target="_top">The Middle East  Upstairs</a> w/ <a href="http://www.versus-ny.co.uk/" target="_top">+-</a>, <a href="http://www.spineless.com/trackstar.html" target="_top">Track Star</a>, and <a href="http://www.kimone.com/" target="_top">Kimone</a>.<br><br></td>
</tr>
<tr>
<td colspan="2"><font><B>Lockgroove - Fall 2001</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>11/17/2001&nbsp;</td>
<td align="left" valign="top"><font>Sat - Philadelphia, PA. - <a href="http://philadelphia.citysearch.com/profile/8957316/" target="_top">The Khyber Pass</a> w/ <a href="http://www.evil-office.net/swirlies/" target="_top">The Swirlies</a> & <a href="http://www.victoriarecords.com/mazarin.html" target="_top">Mazarin</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>11/18/2001&nbsp;</td>
<td align="left" valign="top"><font>Sun - East Hampton, MA. - <a href="http://www.flywheelarts.org/" target="_top">Flywheel</a> w/ <a href="http://www.southern.com/southern/band/LAPSE/" target="_top">The Lapse</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>11/19/2001&nbsp;</td>
<td align="left" valign="top"><font>Mon - Central Square, Cambridge, MA. - <a href="http://www.ttthebears.com" target="_top">TT the Bears Place</a> w/ <a href="http://www.no-fi.com/spectrum/" target="_top">Spectrum</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>11/20/2001&nbsp;</td>
<td align="left" valign="top"><font>Tue - New York, NY. - <a href="http://www.browniesnyc.com/" target="_top">Brownies</a> w/ <a href="http://www.evil-office.net/swirlies/" target="_top">The Swirlies</a> & <a href="http://www.no-fi.com/spectrum/" target="_top">Spectrum</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>12/13/2001&nbsp;</td>
<td align="left" valign="top"><font>Thu - Jamaica Plain, MA. - <a href="http://boston.citysearch.com/profile/11352672" target="_top">Milky Way Lounge and Lanes</a> w/ <a href="http://www.carcrashshow.com/" target="_top">CarCrashShow</a> and <a href="http://www.priapus.com/artists.html" target="_top">Planetarium</a><br><br></td>
</tr>
<!-- end lockgroove dates -->
