<!-- start helloattack dates -->
<tr>
<td colspan="2"><font><B>Hello, Attack! - Spring 2003</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>3/7/2003&nbsp;</td>
<td align="left" valign="top"><font>Fri - Boston, MA - <a href="http://www.icaboston.org/" target="_top">The ICA Boston</a> w/ <a href="http://www.qdivision.com/francine/" target="_top">Francine</a>. Tix available <a href="http://search.cartserver.com/search/search.cgi?cartid=p-2724&category=q&maxhits=40&keywords=icatix&go=GO!" target="_top">here</a>.</td>
</tr>
<tr>
<td align="left" valign="top"><font>4/24/2003&nbsp;</td>
<td align="left" valign="top"><font>Thu - Boston, MA - <a href="http://boston.cc.com/paradise.asp" target="_top">The Paradise Lounge</a>. J will also be DJing. Presented by the <a href="http://www.weeklydig.com/" target="_top">WeeklyDig</a></td>
</tr>
<tr>
<td align="left" valign="top"><font>5/2/2003&nbsp;</td>
<td align="left" valign="top"><font>Fri - Cambridge, MA - <a href="http://www.mideastclub.com" target="_top">The Middle East (Upstairs)</a>. w/ <a href="http://www.acefu.com/modules.php?op=modload&name=News&file=article&sid=80&mode=thread&order=0&thold=0" target="_top">Officer May</a> <i>release party!</i>, <a href="http://www.eyeslikeknives.com/" target="_top">Eyes Like Knives</a> & <a href="http://www.polarismine.com/" target="_top">Polaris Mine</a><br><br></td>
</tr>
<tr>
<td colspan="2"><font><B>Hello, Attack! - Summer 2002</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>7/18/2002&nbsp;</td>
<td align="left" valign="top"><font>Thu - Cambridge, MA - <a href="http://www.mideastclub.com/" target="_top">The Middle East  Upstairs</a> w/ <a href="http://www.mergerecords.com/bands/radar/bio.html" target="_top">Radar Brothers</a> & <a href="http://www.thebeatings.com/" target="_top">The Beatings</a> 18+ $8</td>
</tr>
<tr>
<td align="left" valign="top"><font>9/5/2002&nbsp;</td>
<td align="left" valign="top"><font>Thu - Cambridge, MA - <a href="http://www.mideastclub.com/" target="_top">The Middle East  Upstairs</a> w/ <a href="http://www.hydrahead.com/isis/" target="_top">ISIS</a> (CD Release) & <a href="http://www.27.vg/" target="_top">27</a><br><br></td>
</tr>
<tr>
<td colspan="2"><font><B>Hello, Attack! - Spring 2002</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>4/10/2002&nbsp;</td>
<td align="left" valign="top"><font>Wed - Cambridge, MA - <a href="http://www.mideastclub.com/" target="_top">The Middle East  Upstairs</a> w/ <a href="http://www.theautointeriors.com/" target="_top">Auto Interiors</a> & <a href="http://www.thegoodnorth.com/" target="_top">The Good North</a>. 18+ $8</td>
</tr>
<tr>
<td align="left" valign="top"><font>5/28/2002&nbsp;</td>
<td align="left" valign="top"><font>Tue - Cambridge, MA - <a href="http://www.wmbr.org/shows/pipeline.html" target="_top">88.1 FM - WMBR's Pipeline!</a> 8pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>6/8/2002&nbsp;</td>
<td align="left" valign="top"><font>Sat - Cambridge, MA - <a href="http://www.mideastclub.com/" target="_top">The Middle East  Upstairs</a> w/ <a href="http://www.space-echo.com/liquortricks.htm" target="_top">Liquor Tricks</a> (CD Release), <a href="http://www.kimcheerecords.com/bands/victoryatsea/" target="_top">Victory At Sea</a>, Fall In Love, & Deny Everything 18+ $8<br><br></td>
</tr>
<tr>
<td colspan="2"><font><B>Hello, Attack! - Winter 2002</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>2/14/2002&nbsp;</td>
<td align="left" valign="top"><font>Thurs - Cambridge, MA - <a href="http://www.ttthebears.com" target="_top">T.T. the Bear's Place</a> w/ <a href="http://www.thebeatings.com/" target="_top">The Beatings</a>, <a href="http://www.reverse3.com/" target="_top">Reverse</a>, & <a href="http://papercities.org/thesecrets/" target="_top">The Secrets</a><br><br></td>
</tr>
<!-- end helloattack dates -->