<!-- start Lockgroove dates 
<tr>
<td colspan="2"><font><B>Lockgroove</B></td>
</tr>
<tr>
<td align="left" valign="top"><font>11/5/2004&nbsp;</td>
<td align="left" valign="top"><font>Fri - Cambridge, MA ­ <a href="http://www.mideastclub.com/" target="_top">Middle East Downstairs</a> w/ <a href="http://www.fuzzywuzzy.com" target="_top">Luna</a>. 8:30pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>11/6/2004&nbsp;</td>
<td align="left" valign="top"><font>Sat - New York, NY ­ <a href="http://www.donhills.com/" target="_top">Don Hill's</a> w/ Passenger and <a href="http://www.livingthingsmusic.com" target="_top">Living Things</a>. 9pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>11/7/2004&nbsp;</td>
<td align="left" valign="top"><font>Sun - Philadelphia, PA ­ <a href="http://www.thekhyber.com/" target="_top">The Khyber</a> w/ <a href="http://www.silentleague.com" target="_top">The Silent League</a> (x/Mercury Rev) and The Complete Strategist. 9pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>11/8/2004&nbsp;</td>
<td align="left" valign="top"><font>Mon - Arlington, VA ­ <a href="http://www.galaxyhut.com/" target="_top">Galaxy Hut</a> 8:30 pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>11/9/2004&nbsp;</td>
<td align="left" valign="top"><font>Tue - Asheville, NC ­ <a href="http://www.vincentsearcafe.com/" target="_top">Vincent's Ear</a> w/ <a href="http://www.goodluckcricket.com/hellsayers/" target="_top">Wayne Robbins & the Hellsayers</a>. 8:30 pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>11/10/2004&nbsp;</td>
<td align="left" valign="top"><font>Wed - Knoxville, TN ­ <a href="http://www.thepilotlight.com/" target="_top">The Pilot Light</a> w/ <a href="http://www.goodluckcricket.com/hellsayers/" target="_top">Wayne Robbins & the Hellsayers</a>. 8:30 pm.</td>
</tr>
<tr>
<td align="left" valign="top"><font>11/11/2004&nbsp;</td>
<td align="left" valign="top"><font>Thur - Columbus, OH ­ <a href="http://www.cringe.com/bs/distillery.htm" target="_top">Bernie's Distillery</a> w/ <a href="http://www.seedknowledge.com/echobase/echo" target="_top">Echo Base Sound System</a>. 9:00 pm.<BR><BR></td>
</tr>
end Lockgroove dates -->


